export const DOCUMENT_TABLE_PENDING = 'DOCUMENT_TABLE_PENDING';
export const DOCUMENT_TABLE_SUCCESS = 'DOCUMENT_TABLE_SUCCESS';
export const DOCUMENT_TABLE_ERROR = 'DOCUMENT_TABLE_ERROR';

export const DOCUMENT_PREVIEW_PENDING = 'DOCUMENT_PREVIEW_PENDING';
export const DOCUMENT_PREVIEW_SUCCESS = 'DOCUMENT_PREVIEW_SUCCESS';
export const DOCUMENT_PREVIEW_ERROR = 'DOCUMENT_PREVIEW_ERROR';

export const COMPANY_DATA_SUCCESS = 'COMPANY_DATA_SUCCESS';